Tooltip
GeographicaGS/Latitude-web-components pull request #7
Opened 2019-04-01 10:25 UTC by builtbyedgar

2019-04-03 10:21 UTC, padawannn requested changes

2019-04-03 10:21 UTC, padawannn commented on src/components/tooltip/tooltip.js
> +     * Tooltip position
documentar las posible posiciones

2019-04-03 10:21 UTC, padawannn commented on src/components/geo-logo/geo-logo.html
> +      <img v-if="theme === 'light'" src="@/assets/logos/CARTO-logo-negative.svg" alt="">
lo voy a aprobar pero tenemos que tener en cuenta que esto no va a funcionar. Lo arreglamos en otro PR

2019-04-03 10:21 UTC, padawannn commented on src/components/tooltip/tooltip.js
> +      window.clearTimeout(this.sto)
los setTimeout no podemos reemplazarlos por un delay en la transición. Si es muy complicado lo dejamos así pero es por si tenemos muchos tooltips que esos delais se ejecuten en la tarjeta gráfica

2019-04-03 10:21 UTC, padawannn commented on src/components/tooltip/tooltip.scss
> +// .ltd-tooltip-container {
Borramos todo eso ? jeje

2019-04-03 11:38 UTC, builtbyedgar commented on src/components/tooltip/tooltip.js
> +      window.clearTimeout(this.sto)
🤔 no se me había ocurrido. Le doy una vuelta..

2019-04-03 11:45 UTC, builtbyedgar commented on src/components/tooltip/tooltip.scss
> +// .ltd-tooltip-container {
listo!

2019-04-03 11:45 UTC, builtbyedgar commented on src/components/tooltip/tooltip.js
> +      window.clearTimeout(this.sto)
listo!

2019-04-03 11:49 UTC, builtbyedgar commented on src/components/tooltip/tooltip.js
> +     * Tooltip position
para esto además de documentarlas me gustaría meter una función de validación

2019-04-04 06:08 UTC, padawannn approved these changes

2019-04-04 06:08 UTC, merged